In [11]:
import numpy as np 
a= np.array ([1,2,3])
a 
#quest1

array([1, 2, 3])

In [12]:
import numpy 
a= np.array ([[ 0, 10, 20], [30, 40, 50]])
print (" Original array :")
print (a)
y=10
print (" value bigger than 10 =", a [ a>y])
#quest2

 Original array :
[[ 0 10 20]
 [30 40 50]]
 value bigger than 10 = [20 30 40 50]


In [6]:
import numpy 
a= np.array ([[3.7], [7.9]],dtype = np.float64)
b=  np.array ([[3.7], [7.9]],dtype = np.float64)
z= a+b 
print (z) 
#quest4

[[ 7.4]
 [15.8]]


In [9]:
array1= np.array ([[9, 8, 2 ], [4,6,3]])
print (type(array1))
print ( array1)
x1= int(input())
for x in array1 : 
    for y in x : 
        if x1<y:
            print (y, end= "\n")
#quest3

<class 'numpy.ndarray'>
[[9 8 2]
 [4 6 3]]
4
9
8
6


In [10]:
import numpy 
x= np.random.rand (5,10)
y = x-x.mean ( axis=1, keepdims= True )
print (y)
#quest5

[[ 0.18474214 -0.13158729  0.24872013  0.23555271 -0.25023629  0.24450776
  -0.43707282  0.29513956 -0.15518512 -0.23458078]
 [-0.34409636  0.10981851 -0.13767469  0.32613589  0.00757863 -0.23831019
  -0.31554128  0.24536103  0.57436243 -0.22763396]
 [-0.24118066  0.64168174 -0.31486504  0.29321471 -0.28264879  0.5971745
  -0.03171721 -0.29849549 -0.23178689 -0.13137687]
 [ 0.26074639 -0.05508052  0.0730465  -0.4775745  -0.10072578  0.00082687
   0.48593998 -0.43215482  0.05743218  0.1875437 ]
 [ 0.01241366 -0.30898705  0.25970467 -0.02850821  0.17198797 -0.1678599
  -0.16528011 -0.12951559  0.14293819  0.21310637]]
